-include .env

-include .make.vars

# Auto-detected variables (computed once and stored until "make clean")
.make.vars: docker-compose.yml Makefile
	@echo "# Auto-generated by Makefile, DO NOT EDIT" > $@
# Figure out whether we clone over https or git+ssh (you need a GitHub
# account set up with an ssh public key for the latter)
	@echo _GITHUB_BASE = $(if $(shell ssh -T git@github.com 2>&1|grep 'successful'),git@github.com:,https://github.com/) >> $@
	@echo _HOST_TAR_X = $(shell if [ "$$(uname -s)" = "Linux" ]; then echo "tar -m --overwrite" ; else echo tar; fi) >> $@
	@echo _OPENURL = $(shell if [ "$$(uname -s)" = "Linux" ]; then echo "xdg-open" ; else echo "open"; fi) >> $@
	@keybase fs read /keybase/team/epfl_wp_test/s3-assets-credentials.sh >> $@
	@if ! grep AWS_ACCESS_KEY_ID $@ > /dev/null; then \
	  echo >&2 "##############################################################" ; \
	  echo >&2 "#" ;                                                              \
	  echo >&2 "# WARNING: keybase failure; built Docker images" ;                \
	  echo >&2 "# will be missing the plugins hosted on EPFL's Scality S3" ;      \
	  echo >&2 "# servers." ;                                                     \
	  echo >&2 "#" ;                                                              \
	  echo >&2 "# Assuming you have access to these, please review the error" ;   \
	  echo >&2 "# messages above to troubleshoot." ;                              \
	  echo >&2 "#" ;                                                              \
	  echo >&2 "##############################################################" ; \
	  echo >&2 "Press Return to continue:" ;                                      \
	  read;                                                                       \
	fi


.PHONY: help
help: ## Display this help
	@echo ""
	@echo "                   ┌──────────────────────────────────────┐"
	@echo "                   │                \033[1mwp-dev\033[0m                │"
	@echo "                   ├──────────────────────────────────────┤"
	@echo "                   │ Run a WordPress environment locally. │"
	@echo "                   │  https://github.com/epfl-si/wp-dev   │"
	@echo "                   └──────────────────────────────────────┘"
	@echo "                                           「EPFL ISAS-FSD」"

# The '##@' marker creates sections in the help message, and '##' at the end
# of the name of a rule (after its dependencies, if any) documents it.
	@awk 'BEGIN {FS = ":.*##"; printf "\n\033[1mUsage\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

.PHONY: all
all: checkout git-pull up


WP_MAJOR_VERSION = 6
WP_PHP_IMAGE_URL = quay-its.epfl.ch/svc0041/wp-php
# Get the latest image tag from the https://quay-its.epfl.ch API.
# Note that for some (unknown) reason, the query parameter to limit the number
# of result (`n=200`) is maxed at 100. Using `?last=2025-274` is a quick fix as
# it's not possible to sort them in reverse order or to increase the limit.
_get_latest_image_tag = ./devscripts/curl-authenticated-quay '/v2/svc0041/wp-php/tags/list?last=2025-274' | \
                        jq -r '.tags | map(select(test("^[0-9]{4}-[0-9]{3}$$"))) | last'
# Set WP_PHP_IMAGE_VERSION in a `.env` file to have precedence on the
# _get_latest_image_tag script.
WP_PHP_IMAGE_TAG := $(or $(WP_PHP_IMAGE_VERSION),$(shell $(_get_latest_image_tag)))
# Export WP_PHP_IMAGE_VERSION & WP_NGINX_IMAGE_VERSION variables for docker compose
export WP_PHP_IMAGE_VERSION=${WP_PHP_IMAGE_TAG}
export WP_NGINX_IMAGE_VERSION=${WP_PHP_IMAGE_TAG}

_docker_exec_clinic := docker exec --user www-data -it wp-clinic

############################# Pulling code #####################################
#
# As a matter of taste, we'd rather have Makefile-driven `git clone`s
# than submodules - Plus this lets you substitute your own arrangement
# if you wish.
#
# Code doesn't only get pulled from Git either: src is extracted
# from the "wp-base" Docker image.

.PHONY: checkout
checkout: src wp-ops wp-operator wp-continuous-integration menu-api ## Checkout wp-ops, wp-operator, wp-continuous-integration, menu-api, WP Themes and WP Plugins

src:
	# TODO ensure wp-php
	-rm -f src
	mkdir -p "$@" || true
	chmod 1777 "$@" || true
	# Scratch haz nothing :( need bash or something. FIXME: Use wp-base instead of wp-php
	docker run -d --name wp-php-4-wp-extractor --rm $(WP_PHP_IMAGE_URL):$(WP_PHP_IMAGE_TAG) sleep 100
	# Copy WordPress out of the image
	docker cp wp-php-4-wp-extractor:/wp/. src
	touch $@
	# Ensure "epfl-si" repositories' remote URLs are SSH URL
	./devscripts/ensure-git-ssh-url ./src

_find_git_depots := find . \( -path ./volumes -prune -false \) -o -name .git -prune |xargs -n 1 dirname|grep -v 'ansible-deps-cache'
.PHONY: git-status
git-status: ## Echo the `git status` of subdirectories
	@set -e; for dir in `$(_find_git_depots)`; do (cd $$dir; echo "$$(tput bold)$$dir$$(tput sgr0)"; git status -uno; echo); done

.PHONY: git-pull
git-pull: ## Walk down the directory to find repositories to update (with rebase!)
	@set -e; for dir in `$(_find_git_depots)`; do (cd $$dir; echo "$$(tput bold)$$dir$$(tput sgr0)"; git pull --rebase --autostash; echo); done


########################### Clone sub-repositories #############################
_git_clone = mkdir -p $@ || true; devscripts/ensure-git-clone.sh $(_GITHUB_BASE)$(strip $(1)) $@ $(2); touch $@

wp-ops:
	$(call _git_clone, epfl-si/wp-ops, master)

wp-operator:
	$(call _git_clone, epfl-si/wp-operator)

wp-continuous-integration:
	$(call _git_clone, epfl-si/wp-continuous-integration)

menu-api:
	$(call _git_clone, epfl-si/wp-menu-api, master)


################################################################################
##@ Setup (Building or pulling Docker images)

ensure_wp_base := docker inspect wp-base >/dev/null 2>&1 || $(MAKE) wp-base

.PHONY: wp-base
wp-base: ## Build the WordPress base image, which several other images depend on
	docker build -t quay-its.epfl.ch/svc0041/wp-base:rc \
	--build-arg AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID) \
	--build-arg AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY) \
	wp-ops/docker/wp-base

WPCRON_VER := 2025-001

.PHONY: wp-cron
wp-cron: ## Build the WP-Cron image, based on wp-base image
	docker build -t quay-its.epfl.ch/svc0041/wp-cron:$(WPCRON_VER) \
	wp-ops/docker/wp-cron

.PHONY: docker-build
docker-build: ## Build the Docker images locally
	@$(ensure_wp_base)
	docker compose build $(DOCKER_BUILD_ARGS)

define expand_ver
case "$(VER)" in \
  202[456789]-*) ver="$(VER)" ;; \
  *) ver="$$(date +%Y)-$(VER)" ;; \
esac
endef

.PHONY: wpn
wpn: ## Build the wordpress-nginx and wordpress-php images
ifeq ($(VER),)
	$(error Need a value for VER, e.g., make wpn VER=001)
endif
	@$(ensure_wp_base)

	@$(expand_ver); \
	echo "Building wp-nginx:$$ver & wp-php:$$ver" ; \
	set -e -x; \
	docker build -t quay-its.epfl.ch/svc0041/wp-nginx:$$ver \
		wp-ops/docker/wordpress-nginx ; \
	docker build -t quay-its.epfl.ch/svc0041/wp-php:$$ver \
		wp-ops/docker/wordpress-php

.PHONY: wpn-push
wpn-push: ## Push the wordpress-nginx and wordpress-php images
	@$(expand_ver); \
	echo "Pushing wp-nginx:$$ver & wp-php:$$ver"; \
	set -e -x; \
	  docker push quay-its.epfl.ch/svc0041/wp-nginx:$$ver ; \
	  docker push quay-its.epfl.ch/svc0041/wp-php:$$ver
	@$(expand_ver); \
	echo "\nNow's probably a good time to run ./ansible/wpsible -t wp.web;"; \
	echo "Edit wp-ops/ansible/roles/wordpress-namespace/vars/image-vars.yml,"; \
	echo "or use an extra var: -e \"nginx_deployment_images_tag='$$ver'\""; \
	echo "to change the images version.";

.PHONY: wp-cron-push
wp-cron-push: ## Push the wp-cron image
	docker push quay-its.epfl.ch/svc0041/wp-cron:$(WPCRON_VER) ;

.PHONY: build-apache-redirector
build-apache-redirector: ## Build the apache-redirector image
ifeq ($(VER),)
	$(error Need a value for VER, e.g., make build-apache-redirector VER=001)
endif
	@$(expand_ver); \
	echo "Building apache-redirector:$$ver"; \
	set -e -x; \
	docker build -t quay-its.epfl.ch/svc0041/apache-redirector:$$ver \
		wp-ops/docker/apache-redirector ;

.PHONY: push-apache-redirector
push-apache-redirector: ## Build the apache-redirector image
	@$(expand_ver); \
	echo "Pushing apache-redirector:$$ver"; \
	set -e -x; \
	docker push quay-its.epfl.ch/svc0041/apache-redirector:$$ver


########################################################################
##@ Development Lifecycle

SITE_DIR := /srv/test/wp-httpd/htdocs

.PHONY: up
up: checkout run/nginx/nginx.conf var/wp-data run/wp-nonces/wp-nonces.php run/certs src ## Start up a local WordPress instance
	docker compose up -d
	./devscripts/await-mariadb-ready
	@echo "If you have want to use the wp-gutenberg-epfl plugin or to dev on Gutenberg,"
	@echo "install nvm and run 'make gutenberg'"
	@echo
	$(_OPENURL) https://wordpress.localhost

run/nginx/nginx.conf: nginx-dev.conf
	# FIXME nginx configuration should be generated. Also we need a way to
	# generate a couple of websites in it.
	mkdir -p run/nginx || true
	chmod 1777 run/nginx || true
	cp $< $@

run/wp-nonces/wp-nonces.php:
	mkdir -p run/wp-nonces || true
	chmod 1777 run/wp-nonces || true
	echo "<?php" > run/wp-nonces/wp-nonces.php
	echo "// Generated from https://api.wordpress.org/secret-key/1.1/salt/" >> run/wp-nonces/wp-nonces.php
	curl -s https://api.wordpress.org/secret-key/1.1/salt/ >> run/wp-nonces/wp-nonces.php

# https://stackoverflow.com/a/41366949/960623
run/certs:
	mkdir -p $@ || true
	chmod 1777 $@ || true
	openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
	  -keyout run/certs/wordpress.localhost.key \
	  -out run/certs/wordpress.localhost.crt \
	  -subj "/CN=wordpress.localhost"
	  # -addext "subjectAltName=DNS:wordpress.localhost,DNS:*.example.com,IP:10.0.0.1"
	chmod 666 run/certs/wordpress.localhost*

var/wp-data:
	mkdir -p $@ || true
	chmod 1777 $@ || true

.PHONY: stop
stop: ## Stop the local WordPress instance
	docker compose stop

.PHONY: rm
rm: ## Remove the containers by name
	docker rm -f wp-db wp-menu-api wp-nginx wp-php wp-php wp-pma

.PHONY: down
down: ## Stop the local WordPress instance and delete its containers
	docker compose down

.PHONY: gutenberg
gutenberg: ## Start the development server for Gutenberg
	cd src/plugins/wp-gutenberg-epfl; npm install --silent --no-fund; npm start


########################################################################
##@ Daily Business

.PHONY: exec
exec: ## Enter the management container
	@$(_docker_exec_clinic) bash -l

.PHONY: nginx
nginx: ## Enter the nginx container
	@docker exec -it wp-nginx bash -l

.PHONY: php
php: ## Enter the PHP container
	@docker exec -it wp-php bash -l

.PHONY: mariadb
mariadb: ## Run a MariaDB command-line client
	@$(_docker_exec_clinic) bash -c 'mariadb -p$$MARIADB_ROOT_PASSWORD -u root -h mariadb'

.PHONY: wp-menu-api
wp-menu-api: ## Enter the menu-api container
	@docker exec -it wp-menu-api bash -l


########################################################################
##@ Backup / Restore

.PHONY: backup
backup: ## Backup the current state
	./devscripts/backup-restore backup wordpress-state.tgz

.PHONY: restore
restore: ## Restore the current state
	./devscripts/backup-restore restore wordpress-state.tgz


########################################################################
##@ Observe

.PHONY: logs
logs: ## Follow the docker compose's log
	docker compose logs -f --tail=5

.PHONY: tail-errors
tail-errors: ## Follow the nginx error log
	docker compose logs -f --tail=5 nginx

.PHONY: lnav
lnav:
	@$(_docker_exec_clinic) bash -c 'lnav /srv/*/logs'

.PHONY: tail-sql
tail-sql: ## Activate and follow the MariaDB general query log
	./devscripts/mariadb-general-log tail


########################################################################
##@ Developer Support

CTAGS_FLAGS = --exclude=node_modules $(EXTRA_CTAGS_FLAGS) -R $(CTAGS_TARGETS)

CTAGS_TARGETS = src/*.php \
  src/wp-admin \
  src/wp-includes \
  src/themes/wp-theme-2018 \
  src/plugins/epfl-* \
  src/plugins/polylang \
  src/mu-plugins

tags: checkout ## Index the source code in vim format
	ctags $(CTAGS_FLAGS)

TAGS: checkout ## Index the source code in Emacs ”etags” format
	ctags -e $(CTAGS_FLAGS)


########################################################################
##@ Cleanup

.PHONY: clean-images
clean-images: ## Prune the Docker images
	docker_pulled_images="$$(cat docker-compose.yml | grep 'image: ' | grep -v default.svc | cut -d: -f2-)"; \
	docker_built_images="wp-base $$(shell cat docker-compose.yml | grep 'image: ' | grep default.svc | cut -d: -f2-)"; \
	for image in $$docker_pulled_images $$docker_built_images ; do docker rmi $$image || true; done
	docker image prune

.PHONY: clean
clean: down clean-images ## Tear down generated files and Docker-side state
	rm -f .make.vars TAGS tags

.PHONY: mrproper
mrproper: down ## Mr. Clean will clean your whole house and everything that's in it!
	@echo "Do you want to proceed with the action? This will remove everything. [y/n]: "
	@read answer; \
	if [ "$$answer" = "y" ] || [ "$$answer" = "Y" ]; then \
		echo "Whiping everything..."; \
		OS=$$(uname -s); \
		if [ "$$OS" = "Linux" ]; then \
			echo "This is a Linux system"; \
			sudo rm -rf src run var; \
		elif [ "$$OS" = "Darwin" ]; then \
			echo "This is a macOS system"; \
			rm -rf src run var; \
		else \
			echo "This OS is not supported"; \
		fi \
	else \
		echo "Action canceled."; \
	fi
