#!/bin/sh
#

. "$(dirname "$0")"/functions.sh

usage () {
    die <<"USAGE"

mysql-general-log: Turn MySQL statement log ("general log") on or off

Usage:

   mysql-general-log start
   mysql-general-log stop

You can follow the logs e.g. with

   mysql-general-log tail

USAGE
}

warn_altered_mysql_log_file () {
    warn <<WARN_GENERAL_LOG_FILE
WARNING: the variable 'general_log_file' appears to have been altered;
"$0 tail" may not work.
WARN_GENERAL_LOG_FILE
}

start () {
    # https://stackoverflow.com/a/7470567/435004
    echo 'SET GLOBAL general_log = ON;' | dockermysql mysql
    status >/dev/null
}

stop () {
    echo 'SET GLOBAL general_log = OFF;' | dockermysql mysql
}

status () {
    echo 'SHOW VARIABLES LIKE "general_log%"' | dockermysql mysql
    case $(echo 'SELECT @@general_log_file AS "";' \
               | dockermysql mysql)
    in
        */*) warn_altered_mysql_log_file ; return 2 ;;
        *.log) return 0 ;;
        *)  warn_altered_mysql_log_file ; return 2 ;;
    esac
}

tail () {
    trap stop EXIT HUP INT
    start
    dockermysql "exec tail -F /var/lib/mysql/*.log"
}

set -e

case "$1" in
    start)   start  ;;
    stop)    stop   ;;
    status)  status ;;
    tail)    tail   ;;
    *)       usage  ;;
esac
